input {
  http {
    port => 5044
    codec => json
  }
}

filter {
  # Giữ nguyên dữ liệu JSON gửi vào
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[app_name]}-%{+YYYY.MM.dd}"
  }
  stdout { 
    codec => rubydebug 
  }
}
